### ISSUE TITLE
[Bug]: There is a question with the Gems module

### ISSUE THREAD

**Issue by Ghost067** [magemonkeystudio/divinity#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I installed the gems, the equipment and gems disappeared directly, and there was an error in the console.

### Expected Behavior

When I install gems, gems are mounted to equipment.

### Environment

```markdown
- Server Software: PaperSpigot1.16.5
- Divinity Version: 1.0.0-R0.30
- Codex Version: 1.0.0-R0.29
- Plugins: Only these two plugins.
```

### latest.log

[15:25:30 ERROR]: Could not pass event InventoryCloseEvent to Divinity v1.0.0-R0.30-SNAPSHOT
java.lang.NoSuchFieldError: BOOLEAN
        at studio.magemonkey.divinity.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:101) ~[?:?]
        at studio.magemonkey.divinity.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.persistence.CraftPersistentDataContainer.get(CraftPersistentDataContainer.java:66) ~[patched_1.16.5.jar:git-Paper-794]
        at studio.magemonkey.divinity.stats.items.api.DuplicableItemLoreStat.getRaw(DuplicableItemLoreStat.java:200) ~[?:?]
        at studio.magemonkey.divinity.stats.items.api.DuplicableItemLoreStat.getRaw(DuplicableItemLoreStat.java:191) ~[?:?]
        at studio.magemonkey.divinity.stats.items.attributes.DefenseAttribute.updateItem(DefenseAttribute.java:214) ~[?:?]
        at studio.magemonkey.divinity.manager.listener.object.DynamicStatListener.updateItem(DynamicStatListener.java:31) ~[?:?]
        at studio.magemonkey.divinity.manager.listener.object.DynamicStatListener.lambda$onInvClose$1(DynamicStatListener.java:74) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at studio.magemonkey.divinity.manager.listener.object.DynamicStatListener.onInvClose(DynamicStatListener.java:72) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor755.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1470) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleContainerClose(PlayerConnection.java:2483) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2476) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:20) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:7) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[15:25:33 ERROR]: Could not pass event InventoryCloseEvent to Divinity v1.0.0-R0.30-SNAPSHOT
java.lang.NoSuchFieldError: BOOLEAN
        at studio.magemonkey.divinity.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:101) ~[?:?]
        at studio.magemonkey.divinity.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.persistence.CraftPersistentDataContainer.get(CraftPersistentDataContainer.java:66) ~[patched_1.16.5.jar:git-Paper-794]
        at studio.magemonkey.divinity.stats.items.api.DuplicableItemLoreStat.getRaw(DuplicableItemLoreStat.java:200) ~[?:?]
        at studio.magemonkey.divinity.stats.items.api.DuplicableItemLoreStat.getRaw(DuplicableItemLoreStat.java:191) ~[?:?]
        at studio.magemonkey.divinity.stats.items.attributes.DefenseAttribute.updateItem(DefenseAttribute.java:214) ~[?:?]
        at studio.magemonkey.divinity.manager.listener.object.DynamicStatListener.updateItem(DynamicStatListener.java:31) ~[?:?]
        at studio.magemonkey.divinity.manager.listener.object.DynamicStatListener.lambda$onInvClose$1(DynamicStatListener.java:74) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at studio.magemonkey.divinity.manager.listener.object.DynamicStatListener.onInvClose(DynamicStatListener.java:72) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor755.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1470) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleContainerClose(PlayerConnection.java:2483) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2476) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:20) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:7) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1400) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[15:25:44 INFO]: Ghost067_ issued server command: /gems get 生命石3
[15:25:53 ERROR]: Could not pass event InventoryCloseEvent to Divinity v1.0.0-R0.30-SNAPSHOT
java.lang.NoSuchFieldError: BOOLEAN
        at studio.magemonkey.divinity.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:101) ~[?:?]
        at studio.magemonkey.divinity.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.persistence.CraftPersistentDataContainer.get(CraftPersistentDataContainer.java:66) ~[patched_1.16.5.jar:git-Paper-794]
        at studio.magemonkey.divinity.stats.items.api.DuplicableItemLoreStat.getRaw(DuplicableItemLoreStat.java:200) ~[?:?]
        at studio.magemonkey.divinity.stats.items.api.DuplicableItemLoreStat.getRaw(DuplicableItemLoreStat.java:191) ~[?:?]
        at studio.magemonkey.divinity.stats.items.attributes.DefenseAttribute.updateItem(DefenseAttribute.java:214) ~[?:?]
        at studio.magemonkey.divinity.manager.listener.object.DynamicStatListener.updateItem(DynamicStatListener.java:31) ~[?:?]
        at studio.magemonkey.divinity.manager.listener.object.DynamicStatListener.lambda$onInvClose$1(DynamicStatListener.java:74) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at studio.magemonkey.divinity.manager.listener.object.DynamicStatListener.onInvClose(DynamicStatListener.java:72) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor755.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1470) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleContainerClose(PlayerConnection.java:2483) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2476) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:20) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:7) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1400) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[15:25:54 INFO]: Ghost067_ issued server command: /gems get 生命石2
[15:26:05 ERROR]: Could not pass event InventoryClickEvent to Divinity v1.0.0-R0.30-SNAPSHOT
java.lang.NoSuchFieldError: BOOLEAN
        at studio.magemonkey.divinity.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:101) ~[?:?]
        at studio.magemonkey.divinity.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.persistence.CraftPersistentDataContainer.get(CraftPersistentDataContainer.java:66) ~[patched_1.16.5.jar:git-Paper-794]
        at studio.magemonkey.divinity.stats.items.api.DuplicableItemLoreStat.lambda$getAllRaw$3(DuplicableItemLoreStat.java:218) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at studio.magemonkey.divinity.stats.items.api.DuplicableItemLoreStat.getAllRaw(DuplicableItemLoreStat.java:220) ~[?:?]
        at studio.magemonkey.divinity.stats.items.attributes.api.SimpleStat.get(SimpleStat.java:103) ~[?:?]
        at studio.magemonkey.divinity.stats.items.attributes.api.SimpleStat.getTotal(SimpleStat.java:69) ~[?:?]
        at studio.magemonkey.divinity.stats.items.ItemStats.getStat(ItemStats.java:257) ~[?:?]
        at studio.magemonkey.divinity.stats.items.ItemStats.getStat(ItemStats.java:248) ~[?:?]
        at studio.magemonkey.divinity.stats.items.ItemStats.updateVanillaAttributes(ItemStats.java:301) ~[?:?]
        at studio.magemonkey.divinity.stats.items.api.DuplicableItemLoreStat.add(DuplicableItemLoreStat.java:115) ~[?:?]
        at studio.magemonkey.divinity.modules.api.socketing.ModuleSocket.insertSocket(ModuleSocket.java:395) ~[?:?]
        at studio.magemonkey.divinity.modules.api.socketing.ISocketGUI.open(ISocketGUI.java:192) ~[?:?]
        at studio.magemonkey.divinity.modules.api.socketing.ModuleSocket.startSocketing(ModuleSocket.java:375) ~[?:?]
        at studio.magemonkey.divinity.modules.api.socketing.ModuleSocket.onDragDrop(ModuleSocket.java:182) ~[?:?]
        at studio.magemonkey.divinity.modules.api.socketing.ModuleSocket.onDragDrop(ModuleSocket.java:29) ~[?:?]
        at studio.magemonkey.divinity.modules.api.QModuleDrop.onDragDropEvent(QModuleDrop.java:201) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor769.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Travja** [comment]
I'll have to look at this tomorrow or whenever I have availability next

**Comment by Ghost067** [comment]
On the other hand, through the reaction of my server players, the gem on evasion rate in the Gem module is useless, I hope you will troubleshoot this problem together, thank you.

**Comment by Travja** [comment]
Could you send me the item you're using and the gem that you're applying to it?

**Comment by Ghost067** [comment]
[gems.zip](https://github.com/user-attachments/files/16398621/gems.zip)

This is a zip of the configuration folder for the entire Gems module.

**Comment by Ghost067** [comment]
Add an error message in the console. This error is generated when attacking Mythicmobs monsters after setting damage in the current version of the plugin.

[15:57:34 ERROR]: Could not pass event EntityDamageByEntityEvent to Divinity v1.0.0-R0.30-SNAPSHOT
java.lang.NoSuchFieldError: BOOLEAN
        at studio.magemonkey.divinity.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:101) ~[?:?]
        at studio.magemonkey.divinity.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.persistence.CraftPersistentDataContainer.get(CraftPersistentDataContainer.java:66) ~[patched_1.16.5.jar:git-Paper-794]
        at studio.magemonkey.divinity.stats.items.api.DuplicableItemLoreStat.lambda$getAllRaw$3(DuplicableItemLoreStat.java:218) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at studio.magemonkey.divinity.stats.items.api.DuplicableItemLoreStat.getAllRaw(DuplicableItemLoreStat.java:220) ~[?:?]
        at studio.magemonkey.divinity.stats.items.attributes.DamageAttribute.get(DamageAttribute.java:142) ~[?:?]
        at studio.magemonkey.divinity.stats.EntityStats.getDamageTypes(EntityStats.java:684) ~[?:?]
        at studio.magemonkey.divinity.manager.listener.object.VanillaWrapperListener.onVanillaDamage(VanillaWrapperListener.java:261) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor758.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at me.deecaad.weaponmechanics.weapon.damage.DamageUtil.apply(DamageUtil.java:141) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:117) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:51) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:45) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.HitHandler.handleEntityHit(HitHandler.java:141) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.HitHandler.handleHit(HitHandler.java:56) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.weaponprojectile.WeaponProjectile.updatePosition(WeaponProjectile.java:396) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.AProjectile.tick(AProjectile.java:362) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.ProjectilesRunnable.tickOnAdd(ProjectilesRunnable.java:101) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.ProjectilesRunnable.addProjectile(ProjectilesRunnable.java:68) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.weaponprojectile.Projectile.shoot(Projectile.java:105) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.shoot.ShootHandler.shoot(ShootHandler.java:598) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.shoot.ShootHandler.singleShot(ShootHandler.java:244) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.shoot.ShootHandler.shootWithoutTrigger(ShootHandler.java:228) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.shoot.ShootHandler.tryUse(ShootHandler.java:78) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.WeaponHandler.tryUses(WeaponHandler.java:141) ~[?:?]
        at me.deecaad.weaponmechanics.listeners.trigger.TriggerPlayerListeners.interact(TriggerPlayerListeners.java:219) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor867.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:512) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1766) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:9) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1400) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
